export function Hero() {
    return (
        <div className="hero min-h-screen">
            <div className="hero-content text-center">
                <div className="max-w-md">
                    <h1 className="text-5xl font-bold">New NFTs EVERYDAY</h1>
                    <p className="py-6">Everyday there will be new NFTs autogenerated in all different tiers!</p>
                </div>
            </div>
        </div>
    );
}